# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('correct', models.BooleanField()),
            ],
            options={
                'ordering': ('pk', 'name', 'correct'),
            },
        ),
        migrations.CreateModel(
            name='URLList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_orig', models.CharField(max_length=64)),
                ('url_pos', models.CharField(max_length=64)),
                ('url_neg', models.CharField(max_length=64)),
                ('url_hot', models.CharField(max_length=64)),
                ('orient', models.IntegerField()),
                ('pct', models.IntegerField()),
                ('pred', models.IntegerField()),
                ('prob', models.IntegerField()),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Database')),
            ],
            options={
                'ordering': ('db', '-pct'),
            },
        ),
    ]
