# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url_orig', models.URLField()),
                ('url_pos', models.URLField()),
                ('url_neg', models.URLField()),
                ('url_hot', models.URLField()),
                ('orient', models.IntegerField()),
                ('pct', models.IntegerField()),
                ('pred', models.IntegerField()),
                ('prob', models.IntegerField()),
            ],
            options={
                'ordering': ('pct',),
            },
        ),
        migrations.CreateModel(
            name='Incorrect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url_orig', models.URLField()),
                ('url_pos', models.URLField()),
                ('url_neg', models.URLField()),
                ('url_hot', models.URLField()),
                ('orient', models.IntegerField()),
                ('pct', models.IntegerField()),
                ('pred', models.IntegerField()),
                ('prob', models.IntegerField()),
            ],
            options={
                'ordering': ('pct',),
            },
        ),
    ]
